version: '2.1'
services:
  server:
    build: 
      context: ./site/server
      dockerfile: Dockerfile
    restart: always
  web:
    build:
      context: ./site/web
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production      
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
      - server
    restart: always
    environment:
      DOMAINS: 'ihentai.moe -> http://web:80, api.ihentai.moe -> http://server:80'
      STAGE: 'production'