version: '2.1'
services:
  server:
    build: 
      context: ./site/server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '4929:4929'
    restart: always
  web:
    build:
      context: ./site/web
      dockerfile: Dockerfile
    links:
      - server
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production