version: '2.1'
services:
  server:
    build: 
      context: ./site/server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:80'
  web:
    build:
      context: ./site/web
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production